version: '3'

services:
  java-rest-server:
    image: icodo/java-rest-jenkins-project
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 6s
    networks:
      - javanetwork
    ports:
      - "80:8080"
networks:
  javanetwork:
    driver: overlay
