version: '3.2'

services:
  java-rest-server:
    image: icodo/java-rest-jenkins-project
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 60s
    networks:
      - jenkins
    ports:
      - "8080:8080"
networks:
  java-network:
    driver: overlay
    attachable: true